spring: 
  datasource: 
    url: jdbc.mysql://localhost:3306/testdb
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa: 
    show-sql: true
    generate-ddl: true